version: "3.8"

services:
  frontend-app:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-app
    command: wait-for backend-app:3333 -t 120 -- /usr/local/bin/start.sh
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/home/node/app
    depends_on:
      - backend-app
    networks:
      - network-app

  backend-app:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    container_name: backend-app
    restart: unless-stopped
    command: wait-for database:5432 -t 120 -- /usr/local/bin/start.sh
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/home/node/backend
    depends_on:
      - database
    networks:
      - network-app

  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=bemol
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./_pgData:/var/lib/postgresql/data
    networks:
      - network-app

networks:
  network-app:
    driver: bridge